// Generated from: features\addNewBatchDetails.feature
import { test } from "playwright-bdd";

test.describe('Add New Batch details pop up', () => {

  test.beforeEach('Background: Admin is on the Add new batch pop up', async ({ Given, page, When, Then }) => {
    await Given('Admin is on batch page', null, { page }); 
    await When('Admin clicks on "Add New batch" under the "batch" menu bar'); 
    await Then('Admin should see the Batch Details pop up window'); 
  });
  
  test.describe('Validate cancel button in Batch details pop up', () => {

    test('Example #1', { tag: ['@batch'] }, async ({ Given, When, Then }) => { 
      await Given('Admin is on the Batch Details Pop Up Window'); 
      await When('Admin enter the valid data "TestProgramsa", "88452", "Desc1", "10", "true" fields and clicks cancel button'); 
      await Then('Admin can see the batch "TestProgramsa""88452" details popup closes without creating any batch'); 
    });

    test('Example #2', { tag: ['@batch'] }, async ({ Given, When, Then }) => { 
      await Given('Admin is on the Batch Details Pop Up Window'); 
      await When('Admin enter the valid data "TestProgramsa", "88602", "Desc2", "15", "true" fields and clicks cancel button'); 
      await Then('Admin can see the batch "TestProgramsa""88602" details popup closes without creating any batch'); 
    });

    test('Example #3', { tag: ['@batch'] }, async ({ Given, When, Then }) => { 
      await Given('Admin is on the Batch Details Pop Up Window'); 
      await When('Admin enter the valid data "TestProgramsa", "88901", "Desc3", "20", "true" fields and clicks cancel button'); 
      await Then('Admin can see the batch "TestProgramsa""88901" details popup closes without creating any batch'); 
    });

  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $beforeEach }) => {});
test.afterEach('AfterEach Hooks', ({ $afterEach }) => {});

test.use({
  $test: ({}, use) => use(test),
  $uri: ({}, use) => use('features\\addNewBatchDetails.feature'),
  $bddFileData: ({}, use) => use(bddFileData),
  $beforeEachFixtures: ({ page }, use) => use({ page }),
  $afterEachFixtures: ({ page }, use) => use({ page }),
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":14,"pickleLine":72,"tags":["@batch"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin is on batch page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks on \"Add New batch\" under the \"batch\" menu bar","isBg":true,"stepMatchArguments":[{"group":{"start":16,"value":"\"Add New batch\"","children":[{"start":17,"value":"Add New batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":42,"value":"\"batch\"","children":[{"start":43,"value":"batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the Batch Details pop up window","isBg":true,"stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given Admin is on the Batch Details Pop Up Window","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When Admin enter the valid data \"TestProgramsa\", \"88452\", \"Desc1\", \"10\", \"true\" fields and clicks cancel button","stepMatchArguments":[{"group":{"start":27,"value":"\"TestProgramsa\"","children":[{"start":28,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"88452\"","children":[{"start":45,"value":"88452","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Desc1\"","children":[{"start":54,"value":"Desc1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":62,"value":"\"10\"","children":[{"start":63,"value":"10","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"true\"","children":[{"start":69,"value":"true","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then Admin can see the batch \"TestProgramsa\"\"88452\" details popup closes without creating any batch","stepMatchArguments":[{"group":{"start":24,"value":"\"TestProgramsa\"","children":[{"start":25,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"88452\"","children":[{"start":40,"value":"88452","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":20,"pickleLine":73,"tags":["@batch"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin is on batch page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks on \"Add New batch\" under the \"batch\" menu bar","isBg":true,"stepMatchArguments":[{"group":{"start":16,"value":"\"Add New batch\"","children":[{"start":17,"value":"Add New batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":42,"value":"\"batch\"","children":[{"start":43,"value":"batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the Batch Details pop up window","isBg":true,"stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given Admin is on the Batch Details Pop Up Window","stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When Admin enter the valid data \"TestProgramsa\", \"88602\", \"Desc2\", \"15\", \"true\" fields and clicks cancel button","stepMatchArguments":[{"group":{"start":27,"value":"\"TestProgramsa\"","children":[{"start":28,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"88602\"","children":[{"start":45,"value":"88602","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Desc2\"","children":[{"start":54,"value":"Desc2","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":62,"value":"\"15\"","children":[{"start":63,"value":"15","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"true\"","children":[{"start":69,"value":"true","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then Admin can see the batch \"TestProgramsa\"\"88602\" details popup closes without creating any batch","stepMatchArguments":[{"group":{"start":24,"value":"\"TestProgramsa\"","children":[{"start":25,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"88602\"","children":[{"start":40,"value":"88602","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":26,"pickleLine":74,"tags":["@batch"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given Admin is on batch page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Action","textWithKeyword":"When Admin clicks on \"Add New batch\" under the \"batch\" menu bar","isBg":true,"stepMatchArguments":[{"group":{"start":16,"value":"\"Add New batch\"","children":[{"start":17,"value":"Add New batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":42,"value":"\"batch\"","children":[{"start":43,"value":"batch","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Outcome","textWithKeyword":"Then Admin should see the Batch Details pop up window","isBg":true,"stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given Admin is on the Batch Details Pop Up Window","stepMatchArguments":[]},{"pwStepLine":28,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When Admin enter the valid data \"TestProgramsa\", \"88901\", \"Desc3\", \"20\", \"true\" fields and clicks cancel button","stepMatchArguments":[{"group":{"start":27,"value":"\"TestProgramsa\"","children":[{"start":28,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"88901\"","children":[{"start":45,"value":"88901","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Desc3\"","children":[{"start":54,"value":"Desc3","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":62,"value":"\"20\"","children":[{"start":63,"value":"20","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"true\"","children":[{"start":69,"value":"true","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then Admin can see the batch \"TestProgramsa\"\"88901\" details popup closes without creating any batch","stepMatchArguments":[{"group":{"start":24,"value":"\"TestProgramsa\"","children":[{"start":25,"value":"TestProgramsa","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"88901\"","children":[{"start":40,"value":"88901","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end