import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://shop.webdriver.io/');
  await page.getByRole('link', { name: 'WebdriverIO Trucker Cap $' }).click();
  await page.getByRole('button', { name: 'Add to Cart $' }).click();
  await page.getByRole('combobox').selectOption('Black');
  await page.getByRole('button', { name: 'Add to Cart $' }).click();
  await page.getByRole('button', { name: 'Continue to cart $' }).click();
  await page.getByRole('button', { name: 'Cart icon' }).click();
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.getByRole('button', { name: 'Square Pay' }).click();
  await page.getByLabel('Country Selector').nth(2).selectOption('CA');
  await page.locator('[data-test-id="contact-phone-input"]').nth(1).click();
  await page.locator('[data-test-id="contact-phone-input"]').nth(1).fill('778-844-2323');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Checkout as guest' }).click();
  await page.getByRole('button', { name: 'Place order $' }).click();
  await page.locator('[data-test-id="contact-form"]').getByLabel('Country Selector').selectOption('CA');
  await page.locator('[data-test-id="contact-email-input"]').click();
  await page.locator('[data-test-id="contact-email-input"]').fill('smilealwaz2017@gmail.com');
  await page.getByText('Back to Cart Checkout Express').click();
  await page.locator('.grid-container').click();
  await page.getByRole('combobox').nth(1).selectOption('CA');
  await page.locator('[data-test-id="contact-first-name-input"]').click();
  await page.locator('[data-test-id="contact-first-name-input"]').fill('TestS');
  await page.locator('[data-test-id="contact-last-name-input"]').click();
  await page.locator('[data-test-id="contact-last-name-input"]').fill('mile');
  await page.getByRole('textbox', { name: 'Enter your address here.' }).click();
  await page.locator('label').filter({ hasText: 'Cash App Pay' }).locator('div').nth(1).click();
  await page.locator('label').filter({ hasText: 'Credit Card' }).locator('div').nth(1).click();
  await page.getByRole('button', { name: 'Place order $' }).click();
  await page.locator('[data-test-id="contact-form"]').getByLabel('Country Selector').selectOption('CA');
  await page.locator('[data-test-id="contact-phone-input"]').click();
  await page.locator('[data-test-id="contact-phone-input"]').fill('604-592-2944');
  await page.getByRole('button', { name: 'Place order $' }).click();
  await page.getByLabel('Country Selector').nth(1).selectOption('CA');
  await page.locator('iframe[name="single-card-fd56c139-0589-12ff-bb39-d02f168b5db4"]').contentFrame().getByRole('textbox', { name: 'Card number' }).click();
});